"""Bake a TTF into one bitmap-font atlas for Roblox.

Usage: python art/fonts/bitmap_font.py <font.ttf> <Name> [pixel size]

For a pixel font, pass its native size (where every font pixel lands on one image pixel;
Jersey 15 is 27). The script notices the hard edges and marks the font Pixelated, so Roblox
scales it up without blurring.

Writes:
  art/fonts/<Name>.png            white glyphs on transparent, one image for the whole font
  src/shared/Fonts/<Name>.luau    glyph rectangles and metrics read by BitmapText

Upload the PNG once, then put its asset id in the generated module's Image field
(re-running the script keeps the id that is already there).
"""

import math
import os
import re
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CHARS = [chr(code) for code in range(32, 127)]
PADDING = 4  # transparent pixels around each glyph so filtering never bleeds into a neighbour
MAX_SIZE = 1024  # Roblox downscales bigger images


def main() -> None:
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    ttf, name = sys.argv[1], sys.argv[2]
    size = int(sys.argv[3]) if len(sys.argv) > 3 else 96
    font = ImageFont.truetype(ttf, size)
    ascent, descent = font.getmetrics()

    glyphs = []
    for char in CHARS:
        left, top, right, bottom = font.getbbox(char)
        advance = font.getlength(char)
        glyphs.append({
            "char": char,
            "left": left,
            "top": top,
            "width": max(right - left, 0) if bottom > top else 0,
            "height": max(bottom - top, 0),
            "advance": advance,
        })

    # Shelf packing: rows of glyphs, wrapping at the atlas width.
    width = MAX_SIZE
    x = y = 0
    row_height = 0
    for glyph in glyphs:
        if glyph["width"] == 0 or glyph["height"] == 0:
            glyph["x"] = glyph["y"] = 0
            continue
        cell_w = glyph["width"] + PADDING * 2
        cell_h = glyph["height"] + PADDING * 2
        if x + cell_w > width:
            x = 0
            y += row_height
            row_height = 0
        glyph["x"] = x + PADDING
        glyph["y"] = y + PADDING
        x += cell_w
        row_height = max(row_height, cell_h)
    height = y + row_height
    if height > MAX_SIZE:
        sys.exit(f"Atlas is {height}px tall; use a smaller pixel size than {size}")
    height = 2 ** math.ceil(math.log2(height))

    atlas = Image.new("RGBA", (width, height), (255, 255, 255, 0))
    draw = ImageDraw.Draw(atlas)
    for glyph in glyphs:
        if glyph["width"] > 0 and glyph["height"] > 0:
            draw.text((glyph["x"] - glyph["left"], glyph["y"] - glyph["top"]), glyph["char"], font=font, fill=(255, 255, 255, 255))
    # Almost no half-covered pixels means a pixel font at its native size: snap the few stray
    # edge pixels (descenders off the grid) and let Roblox scale it up with hard edges.
    alpha = atlas.getchannel("A")
    histogram = alpha.histogram()
    pixelated = sum(histogram[1:255]) <= histogram[255] * 0.01
    if pixelated:
        atlas.putalpha(alpha.point(lambda value: 255 if value >= 128 else 0))
    png_path = os.path.join(ROOT, "art", "fonts", f"{name}.png")
    atlas.save(png_path)

    module_path = os.path.join(ROOT, "src", "shared", "Fonts", f"{name}.luau")
    image = "rbxassetid://0"
    if os.path.exists(module_path):
        with open(module_path, encoding="utf-8") as existing:
            match = re.search(r'Image = "([^"]+)"', existing.read())
            if match:
                image = match.group(1)

    lines = [
        "--!strict",
        f"-- Generated by art/fonts/bitmap_font.py from {os.path.basename(ttf)} at {size}px. Do not edit by hand.",
        "",
        'local BitmapFont = require(script.Parent.Parent:WaitForChild("Util"):WaitForChild("BitmapFont"))',
        "",
        "local font: BitmapFont.Font = {",
        f'\tImage = "{image}",',
        f"\tAtlasSize = Vector2.new({width}, {height}),",
        f"	Pixelated = {'true' if pixelated else 'false'},",
        f"\tAscent = {ascent},",
        f"\tLineHeight = {ascent + descent},",
        "\tGlyphs = {",
    ]
    for glyph in glyphs:
        lines.append(
            f"\t\t[{ord(glyph['char'])}] = {{ X = {glyph['x']}, Y = {glyph['y']}, Width = {glyph['width']}, "
            f"Height = {glyph['height']}, Left = {glyph['left']}, Top = {glyph['top']}, Advance = {glyph['advance']:g} }}, -- {glyph['char']}"
        )
    lines += ["\t},", "}", "", "return font", ""]
    os.makedirs(os.path.dirname(module_path), exist_ok=True)
    with open(module_path, "w", encoding="utf-8", newline="\n") as out:
        out.write("\n".join(lines))
    print(f"{png_path} ({width}x{height}, pixelated={pixelated}), {module_path}")


if __name__ == "__main__":
    main()
